import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'app.dart';
import 'models/category.dart';
import 'models/transaction.dart';
import 'models/recurring_rule.dart';
import 'models/budget.dart';
import 'services/storage_service.dart';
import 'services/recurring_service.dart';
import 'services/streak_service.dart';
import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();

  // Register adapters (auto-generated by build_runner)
  Hive.registerAdapter(CategoryAdapter());
  Hive.registerAdapter(TransactionAdapter());
  Hive.registerAdapter(RecurringRuleAdapter());
  Hive.registerAdapter(BudgetAdapter());

  // Open boxes
  await Hive.openBox<Category>('categories');
  await Hive.openBox<Transaction>('transactions');
  await Hive.openBox<RecurringRule>('recurringRules');
  await Hive.openBox<Budget>('budgets');
  await Hive.openBox('settings');

  // ── Seed default categories on first launch ──
  final storageService = StorageService();
  await storageService.seedDefaultCategories();

  // ── Initialization: recurring, streaks, notifications ──
  RecurringService(storageService).processDueRecurringRules();
  await StreakService.checkAndUpdateStreak(storageService);

  final notificationService = NotificationService();
  await notificationService.initialize();
  await notificationService.checkBudgetThresholds(storageService);

  runApp(const ProviderScope(child: FinTrackApp()));
}
